CREATE TABLE COMTNDEPTJOB
(
  DEPT_JOB_ID          CHAR(20 BYTE),
  DEPT_JOBBX_ID        CHAR(6 BYTE),
  DEPT_JOB_NM          VARCHAR2(255 BYTE),
  DEPT_JOB_CN          VARCHAR2(2500 BYTE),
  ATCH_FILE_ID         CHAR(20 BYTE),
  CHARGER_ID           VARCHAR2(20 BYTE),
  PRIORT               CHAR(1 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNLEADERSCHDUL
(
  SCHDUL_ID            CHAR(20 BYTE),
  SCHDUL_SE            CHAR(1 BYTE),
  SCHDUL_NM            VARCHAR2(255 BYTE),
  SCHDUL_CN            VARCHAR2(2500 BYTE),
  SCHDUL_PLACE         VARCHAR2(255 BYTE),
  LEADER_ID            VARCHAR2(20 BYTE),
  REPTIT_SE_CODE       CHAR(1 BYTE),
  SCHDUL_BGNDE         CHAR(12 BYTE),
  SCHDUL_ENDDE         CHAR(12 BYTE),
  SCHDUL_CHARGER_ID    VARCHAR2(20 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNDEPTJOBBX
(
  DEPT_JOBBX_ID        CHAR(6 BYTE),
  DEPT_JOBBX_NM        VARCHAR2(255 BYTE),
  DEPT_ID              VARCHAR2(20 BYTE),
  INDICT_ORDR          NUMBER(6),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNLEADERSCHDULDE
(
  SCHDUL_ID  CHAR(20 BYTE),
  SCHDUL_DE  CHAR(8 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNMEMOREPRT
(
  REPRT_ID               CHAR(6 BYTE),
  REPRT_SJ               VARCHAR2(255 BYTE),
  REPRT_DE               CHAR(8 BYTE),
  WRTER_ID               VARCHAR2(20 BYTE),
  REPORTR_ID             VARCHAR2(20 BYTE),
  REPRT_CN               VARCHAR2(2500 BYTE),
  DRCT_MATTER            VARCHAR2(2500 BYTE),
  DRCT_MATTER_REGIST_DT  VARCHAR2(14 BYTE),
  REPORTR_INQIRE_DT      VARCHAR2(14 BYTE),
  FRST_REGISTER_ID       VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM    DATE,
  LAST_UPDUSR_ID         VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM      DATE,
  ATCH_FILE_ID           CHAR(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNMEMOTODO
(
  TODO_ID              CHAR(20 BYTE),
  TODO_NM              VARCHAR2(255 BYTE),
  TODO_BEGIN_TIME      VARCHAR2(14 BYTE),
  TODO_END_TIME        VARCHAR2(14 BYTE),
  WRTER_ID             VARCHAR2(20 BYTE),
  TODO_CN              VARCHAR2(2500 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNWIKMNTHNGREPRT
(
  REPRT_ID             CHAR(6 BYTE),
  REPRT_SE             CHAR(1 BYTE),
  REPRT_SJ             VARCHAR2(255 BYTE),
  REPRT_DE             CHAR(8 BYTE),
  WRTER_ID             VARCHAR2(20 BYTE),
  REPORTR_ID           VARCHAR2(20 BYTE),
  REPRT_BGNDE          CHAR(8 BYTE),
  REPRT_ENDDE          CHAR(8 BYTE),
  REPRT_THSWIK_CN      CLOB,
  REPRT_LESSEE_CN      CLOB,
  PARTCLR_MATTER       VARCHAR2(2500 BYTE),
  ATCH_FILE_ID         CHAR(20 BYTE),
  CONFM_DT             VARCHAR2(14 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTHDBMNTRNGLOGINFO
(
  LOG_ID               CHAR(20 BYTE),
  DATA_SOURC_NM        VARCHAR2(60 BYTE),
  SERVER_NM            VARCHAR2(60 BYTE),
  DBMS_KIND            VARCHAR2(2 BYTE),
  CECK_SQL             VARCHAR2(250 BYTE),
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  MNTRNG_STTUS         CHAR(2 BYTE),
  LOG_INFO             VARCHAR2(2000 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTHTRSMRCVMNTRNGLOGINFO
(
  LOG_ID               CHAR(20 BYTE),
  CNTC_ID              CHAR(8 BYTE),
  TEST_CLASS_NM        VARCHAR2(255 BYTE),
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  MNTRNG_STTUS         CHAR(2 BYTE),
  LOG_INFO             VARCHAR2(2000 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNSERVERRESRCELOGINFO
(
  SERVER_ID            CHAR(20 BYTE),
  SERVER_EQPMN_ID      VARCHAR2(20 BYTE),
  LOG_ID               CHAR(20 BYTE),
  CPU_USE_RT           NUMBER(3),
  MORY_USE_RT          NUMBER(3),
  SVC_STTUS            CHAR(2 BYTE),
  LOG_INFO             VARCHAR2(2000 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNFILESYSMNTRNGLOGINFO
(
  FILE_SYS_ID          CHAR(20 BYTE),
  LOG_ID               CHAR(20 BYTE),
  FILE_SYS_NM          VARCHAR2(60 BYTE),
  FILE_SYS_MANAGE_NM   VARCHAR2(255 BYTE),
  FILE_SYS_MG          NUMBER(8),
  FILE_SYS_THRHLD      NUMBER(8),
  FILE_SYS_USGQTY      NUMBER(8),
  MNTRNG_STTUS         CHAR(2 BYTE),
  LOG_INFO             VARCHAR2(2000 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNPROXYINFO
(
  PROXY_ID             CHAR(20 BYTE),
  PROXY_NM             VARCHAR2(60 BYTE),
  PROXY_IP             VARCHAR2(23 BYTE),
  PROXY_PORT           VARCHAR2(10 BYTE),
  TRGET_SVC_NM         VARCHAR2(255 BYTE),
  SVC_DC               VARCHAR2(2000 BYTE),
  SVC_IP               VARCHAR2(23 BYTE),
  SVC_PORT             VARCHAR2(10 BYTE),
  SVC_STTUS            CHAR(2 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNPROXYLOGINFO
(
  PROXY_ID             CHAR(20 BYTE),
  LOG_ID               VARCHAR2(20 BYTE),
  CLNT_IP              VARCHAR2(23 BYTE),
  CLNT_PORT            VARCHAR2(10 BYTE),
  CONECT_TIME          DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNNTWRKSVCMNTRNGLOGINFO
(
  SYS_IP               VARCHAR2(23 BYTE),
  SYS_PORT             NUMBER(5),
  LOG_ID               CHAR(20 BYTE),
  SYS_NM               VARCHAR2(255 BYTE),
  MNTRNG_STTUS         CHAR(2 BYTE),
  LOG_INFO             VARCHAR2(2000 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNSYNCHRNSERVERINFO
(
  SERVER_ID            CHAR(20 BYTE),
  SERVER_NM            VARCHAR2(60 BYTE),
  SERVER_IP            VARCHAR2(23 BYTE),
  SERVER_PORT          VARCHAR2(10 BYTE),
  FTP_ID               VARCHAR2(20 BYTE),
  FTP_PASSWORD         VARCHAR2(20 BYTE),
  SYNCHRN_LC           VARCHAR2(255 BYTE),
  REFLCT_AT            CHAR(1 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNTRSMRCVMNTRNG
(
  CNTC_ID              CHAR(8 BYTE),
  TEST_CLASS_NM        VARCHAR2(255 BYTE),
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  MNTRNG_STTUS         CHAR(2 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNPROCESSMONLOGINFO
(
  LOG_ID               VARCHAR2(20 BYTE),
  PROCESS_ID           VARCHAR2(20 BYTE),
  PROCESS_NM           VARCHAR2(60 BYTE),
  PROCS_STTUS          VARCHAR2(3 BYTE),
  CREAT_DT             DATE,
  LOG_INFO             VARCHAR2(2000 BYTE),
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNDBMNTRNG
(
  DATA_SOURC_NM        VARCHAR2(60 BYTE),
  SERVER_NM            VARCHAR2(60 BYTE),
  DBMS_KIND            VARCHAR2(2 BYTE),
  CECK_SQL             VARCHAR2(250 BYTE),
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  MNTRNG_STTUS         CHAR(2 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNNTWRKSVCMNTRNG
(
  SYS_IP               VARCHAR2(23 BYTE),
  SYS_PORT             NUMBER(5),
  SYS_NM               VARCHAR2(255 BYTE),
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  MNTRNG_STTUS         CHAR(2 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNFILESYSMNTRNG
(
  FILE_SYS_ID          CHAR(20 BYTE),
  FILE_SYS_NM          VARCHAR2(60 BYTE),
  FILE_SYS_MANAGE_NM   VARCHAR2(255 BYTE),
  FILE_SYS_MG          NUMBER(8),
  FILE_SYS_THRHLD      NUMBER(8),
  FILE_SYS_USGQTY      NUMBER(8),
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  MNTRNG_STTUS         CHAR(2 BYTE),
  CREAT_DT             DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNHTTPMON
(
  SYS_ID               VARCHAR2(20 BYTE),
  SITE_URL             VARCHAR2(100 BYTE),
  WEB_KIND             VARCHAR2(20 BYTE),
  HTTP_STTUS_CD        VARCHAR2(3 BYTE),
  CREAT_DT             DATE,
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTHHTTPMONLOGINFO
(
  SYS_ID               VARCHAR2(20 BYTE),
  LOG_ID               VARCHAR2(20 BYTE),
  SITE_URL             VARCHAR2(100 BYTE),
  WEB_KIND             VARCHAR2(20 BYTE),
  WEB_KIND_NM          VARCHAR2(20 BYTE),
  HTTP_STTUS_CD        VARCHAR2(3 BYTE),
  CREAT_DT             DATE,
  LOG_INFO             VARCHAR2(2000 BYTE),
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNPROCESSMON
(
  PROCESS_ID           VARCHAR2(20 BYTE),
  PROCESS_NM           VARCHAR2(60 BYTE),
  PROCS_STTUS          VARCHAR2(3 BYTE),
  CREAT_DT             DATE,
  MNGR_NM              VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNNOTE
(
  NOTE_ID              CHAR(20 BYTE),
  NOTE_SJ              VARCHAR2(255 BYTE),
  NOTE_CN              VARCHAR2(4000 BYTE),
  ATCH_FILE_ID         CHAR(20 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBNDTCECKMANAGE
(
  BNDT_CECK_SE         VARCHAR2(2 BYTE),
  BNDT_CECK_CD         VARCHAR2(10 BYTE),
  BNDT_CECK_CD_NM      VARCHAR2(255 BYTE),
  USE_AT               CHAR(1 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBNDTDIARY
(
  BNDT_ID              VARCHAR2(20 BYTE),
  BNDT_DE              CHAR(8 BYTE),
  BNDT_CECK_SE         VARCHAR2(2 BYTE),
  BNDT_CECK_CD         VARCHAR2(10 BYTE),
  CHCK_STTUS           VARCHAR2(1000 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNNOTETRNSMIT
(
  NOTE_ID              CHAR(20 BYTE),
  NOTE_TRNSMIT_ID      CHAR(20 BYTE),
  TRNSMITER_ID         VARCHAR2(20 BYTE),
  DELETE_YN            CHAR(1 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNRSS
(
  RSS_ID               CHAR(20 BYTE),
  TRGET_SVC_NM         VARCHAR2(255 BYTE),
  TRGET_SVC_TABLE      VARCHAR2(255 BYTE),
  TRGET_SVC_LIST_CO    NUMBER(5)                DEFAULT 0,
  HDER_TITLE           VARCHAR2(255 BYTE),
  HDER_LINK            VARCHAR2(255 BYTE),
  HDER_DESCRIPTION     VARCHAR2(4000 BYTE),
  HDER_TAG             VARCHAR2(255 BYTE),
  HDER_ETC             VARCHAR2(255 BYTE),
  BDT_TITLE            VARCHAR2(255 BYTE),
  BDT_LINK             VARCHAR2(255 BYTE),
  BDT_DESCRIPTION      VARCHAR2(4000 BYTE),
  BDT_TAG              VARCHAR2(255 BYTE),
  BDT_ETC              VARCHAR2(255 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNNOTERECPTN
(
  NOTE_ID              CHAR(20 BYTE),
  NOTE_TRNSMIT_ID      CHAR(20 BYTE),
  NOTE_RECPTN_ID       CHAR(20 BYTE),
  RCVER_ID             VARCHAR2(20 BYTE),
  OPEN_YN              CHAR(1 BYTE),
  RECPTN_SE            CHAR(2 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNMTGPLACERESVE
(
  RESVE_ID             CHAR(20 BYTE),
  MTG_PLACE_ID         CHAR(20 BYTE),
  MTG_SJ               VARCHAR2(100 BYTE),
  RESVE_MAN_ID         VARCHAR2(20 BYTE),
  RESVE_DE             CHAR(8 BYTE),
  RESVE_BEGIN_TM       VARCHAR2(14 BYTE),
  RESVE_END_TM         VARCHAR2(14 BYTE),
  ATNDNC_NMPR          NUMBER(10),
  MTG_CN               VARCHAR2(200 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNVCATNMANAGE
(
  APPLCNT_ID           VARCHAR2(20 BYTE),
  VCATN_SE             VARCHAR2(2 BYTE),
  BGNDE                CHAR(8 BYTE),
  ENDDE                CHAR(8 BYTE),
  VCATN_RESN           VARCHAR2(200 BYTE),
  REQST_DE             CHAR(8 BYTE),
  OCCRRNC_YEAR         CHAR(4 BYTE),
  SANCTNER_ID          VARCHAR2(20 BYTE),
  CONFM_AT             CHAR(1 BYTE),
  SANCTN_DT            DATE,
  RETURN_RESN          VARCHAR2(1000 BYTE),
  INFRML_SANCTN_ID     CHAR(20 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE,
  NOON_SE              CHAR(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNINDVDLYRYCMANAGE
(
  OCCRRNC_YEAR         CHAR(4 BYTE),
  USID                 VARCHAR2(20 BYTE),
  OCCRNC_YRYC_CO       NUMBER(5,1),
  USE_YRYC_CO          NUMBER(5,1),
  REMNDR_YRYC_CO       NUMBER(5,1),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNRWARDMANAGE
(
  RWARD_ID             CHAR(20 BYTE),
  RWARD_MAN_ID         VARCHAR2(20 BYTE),
  RWARD_CD             VARCHAR2(2 BYTE),
  RWARD_DE             CHAR(8 BYTE),
  RWARD_NM             VARCHAR2(255 BYTE),
  PBLEN_CN             VARCHAR2(1000 BYTE),
  SANCTNER_ID          VARCHAR2(20 BYTE),
  CONFM_AT             CHAR(1 BYTE),
  SANCTN_DT            DATE,
  RETURN_RESN          VARCHAR2(1000 BYTE),
  ATCH_FILE_ID         CHAR(20 BYTE),
  INFRML_SANCTN_ID     CHAR(20 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNCTSNNMANAGE
(
  CTSNN_ID             CHAR(20 BYTE),
  USID                 VARCHAR2(20 BYTE),
  CTSNN_CD             VARCHAR2(2 BYTE),
  REQST_DE             CHAR(8 BYTE),
  CTSNN_NM             VARCHAR2(255 BYTE),
  TRGTER_NM            VARCHAR2(20 BYTE),
  BRTH                 CHAR(8 BYTE),
  OCCRR_DE             CHAR(8 BYTE),
  RELATE               VARCHAR2(2 BYTE),
  REMARK               VARCHAR2(2500 BYTE),
  SANCTNER_ID          VARCHAR2(20 BYTE),
  CONFM_AT             CHAR(1 BYTE),
  SANCTN_DT            DATE,
  RETURN_RESN          VARCHAR2(1000 BYTE),
  INFRML_SANCTN_ID     CHAR(20 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNFXTRSMANAGE
(
  FXTRS_CD             VARCHAR2(14 BYTE),
  FXTRS_NM             VARCHAR2(100 BYTE),
  MAKR_NM              VARCHAR2(100 BYTE),
  PRICE                NUMBER(16),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNEVENTMANAGE
(
  EVENT_ID              CHAR(20 BYTE),
  EVENT_SE              VARCHAR2(2 BYTE),
  EVENT_NM              VARCHAR2(60 BYTE),
  EVENT_PURPS           VARCHAR2(200 BYTE),
  EVENT_BEGIN_DE        CHAR(8 BYTE),
  EVENT_END_DE          CHAR(8 BYTE),
  EVENT_AUSPC_INSTT_NM  VARCHAR2(60 BYTE),
  EVENT_MNGT_INSTT_NM   VARCHAR2(60 BYTE),
  EVENT_PLACE           VARCHAR2(200 BYTE),
  EVENT_CN              VARCHAR2(1000 BYTE),
  CT_OCCRRNC_AT         VARCHAR2(1 BYTE),
  PARTCPT_CT            NUMBER(16),
  GARDEN                NUMBER(10),
  REFRN_URL             VARCHAR2(1024 BYTE),
  RCEPT_BEGIN_DE        CHAR(8 BYTE),
  RCEPT_END_DE          CHAR(8 BYTE),
  FRST_REGISTER_ID      VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM   DATE,
  LAST_UPDUSR_ID        VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNMTGPLACEFXTRS
(
  MTG_PLACE_ID         CHAR(20 BYTE),
  FXTRS_CD             VARCHAR2(14 BYTE),
  QUANTITY             NUMBER(20),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNMTGPLACEMANAGE
(
  MTG_PLACE_ID         CHAR(20 BYTE),
  MTG_PLACE_NM         VARCHAR2(255 BYTE),
  OPN_BEGIN_TM         VARCHAR2(6 BYTE),
  OPN_END_TM           VARCHAR2(6 BYTE),
  ACEPTNC_POSBL_NMPR   NUMBER(10),
  LC_SE                VARCHAR2(5 BYTE),
  LC_DETAIL            VARCHAR2(200 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE,
  ATCH_FILE_ID         CHAR(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNANNVRSRYMANAGE
(
  ANN_ID               CHAR(20 BYTE),
  USID                 VARCHAR2(20 BYTE),
  ANNVRSRY_SE          VARCHAR2(2 BYTE),
  ANNVRSRY_DE          CHAR(8 BYTE),
  CLDR_SE              VARCHAR2(2 BYTE),
  ANNVRSRY_NM          VARCHAR2(255 BYTE),
  ANNVRSRY_SETUP       VARCHAR2(1 BYTE),
  ANNVRSRY_BEGIN_DE    CHAR(8 BYTE),
  MEMO                 VARCHAR2(1000 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE,
  REPTIT_SE            CHAR(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBNDTMANAGE
(
  BNDT_ID              VARCHAR2(20 BYTE),
  BNDT_DE              CHAR(8 BYTE),
  REMARK               VARCHAR2(2500 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNEVENTATDRN
(
  APPLCNT_ID           VARCHAR2(20 BYTE),
  EVENT_ID             CHAR(20 BYTE),
  REQST_DE             CHAR(8 BYTE),
  SANCTNER_ID          VARCHAR2(20 BYTE),
  CONFM_AT             CHAR(1 BYTE),
  SANCTN_DT            DATE,
  RETURN_RESN          VARCHAR2(1000 BYTE),
  INFRML_SANCTN_ID     CHAR(20 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNTWITTER
(
  USID                 CHAR(20 BYTE),
  CONSUMER_KEY         VARCHAR2(50 BYTE),
  CONSUMER_SECRET      VARCHAR2(50 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNINFRMLSANCTN
(
  INFRML_SANCTN_ID     CHAR(20 BYTE),
  JOB_SE_CODE          CHAR(3 BYTE),
  APPLCNT_ID           VARCHAR2(20 BYTE),
  REQST_DE             CHAR(8 BYTE),
  SANCTNER_ID          VARCHAR2(20 BYTE),
  CONFM_AT             CHAR(1 BYTE),
  SANCTN_DT            DATE,
  RETURN_RESN          VARCHAR2(1000 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNWIKIBKMK
(
  WIKI_BKMK_ID         CHAR(20 BYTE),
  USID                 CHAR(20 BYTE),
  WIKI_BKMK_NM         VARCHAR2(1000 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNSERVERINFO
(
  SERVER_ID            CHAR(20 BYTE),
  SERVER_NM            VARCHAR2(60 BYTE),
  SERVER_KND           CHAR(2 BYTE),
  REGST_YMD            CHAR(8 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNSERVEREQPMNINFO
(
  SERVER_EQPMN_ID      VARCHAR2(20 BYTE),
  SERVER_EQPMN_NM      VARCHAR2(60 BYTE),
  SERVER_EQPMN_IP      VARCHAR2(23 BYTE),
  SERVER_EQPMN_MNGR    VARCHAR2(60 BYTE),
  MNGR_EMAIL_ADDR      VARCHAR2(50 BYTE),
  OPERSYSM_INFO        VARCHAR2(2000 BYTE),
  CPU_INFO             VARCHAR2(2000 BYTE),
  MORY_INFO            VARCHAR2(2000 BYTE),
  HDDISK               VARCHAR2(2000 BYTE),
  ETC_INFO             VARCHAR2(2000 BYTE),
  REGST_YMD            CHAR(8 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBACKUPSCHDULDFK
(
  BACKUP_OPERT_ID       VARCHAR2(20 BYTE),
  EXECUT_SCHDUL_DFK_SE  VARCHAR2(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNSERVEREQPMNRELATE
(
  SERVER_ID            CHAR(20 BYTE),
  SERVER_EQPMN_ID      VARCHAR2(20 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBACKUPRESULT
(
  BACKUP_RESULT_ID     VARCHAR2(20 BYTE),
  BACKUP_OPERT_ID      VARCHAR2(20 BYTE),
  BACKUP_FILE          VARCHAR2(255 BYTE),
  STTUS                VARCHAR2(2 BYTE),
  ERROR_INFO           VARCHAR2(2000 BYTE),
  EXECUT_BEGIN_TIME    VARCHAR2(14 BYTE),
  EXECUT_END_TIME      VARCHAR2(14 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBACKUPOPERT
(
  BACKUP_OPERT_ID       VARCHAR2(20 BYTE),
  BACKUP_OPERT_NM       VARCHAR2(60 BYTE),
  BACKUP_ORGINL_DRCTRY  VARCHAR2(255 BYTE),
  BACKUP_STRE_DRCTRY    VARCHAR2(255 BYTE),
  CMPRS_SE              VARCHAR2(2 BYTE),
  EXECUT_CYCLE          VARCHAR2(2 BYTE),
  EXECUT_SCHDUL_DE      CHAR(8 BYTE),
  EXECUT_SCHDUL_HOUR    CHAR(2 BYTE),
  EXECUT_SCHDUL_MNT     CHAR(2 BYTE),
  EXECUT_SCHDUL_SECND   CHAR(2 BYTE),
  USE_AT                CHAR(1 BYTE),
  FRST_REGISTER_ID      VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM   DATE,
  LAST_UPDUSR_ID        VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBATCHSCHDULDFK
(
  BATCH_SCHDUL_ID       VARCHAR2(20 BYTE),
  EXECUT_SCHDUL_DFK_SE  VARCHAR2(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBATCHOPERT
(
  BATCH_OPERT_ID       VARCHAR2(20 BYTE),
  BATCH_OPERT_NM       VARCHAR2(60 BYTE),
  BATCH_PROGRM         VARCHAR2(255 BYTE),
  PARAMTR              VARCHAR2(250 BYTE),
  USE_AT               CHAR(1 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBATCHRESULT
(
  BATCH_RESULT_ID      VARCHAR2(20 BYTE),
  BATCH_SCHDUL_ID      VARCHAR2(20 BYTE),
  BATCH_OPERT_ID       VARCHAR2(20 BYTE),
  PARAMTR              VARCHAR2(250 BYTE),
  STTUS                VARCHAR2(2 BYTE),
  ERROR_INFO           VARCHAR2(2000 BYTE),
  EXECUT_BEGIN_TIME    VARCHAR2(14 BYTE),
  EXECUT_END_TIME      VARCHAR2(14 BYTE),
  LAST_UPDUSR_PNTTM    DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  FRST_REGISTER_ID     VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNBATCHSCHDUL
(
  BATCH_SCHDUL_ID      VARCHAR2(20 BYTE),
  BATCH_OPERT_ID       VARCHAR2(20 BYTE),
  EXECUT_CYCLE         VARCHAR2(2 BYTE),
  EXECUT_SCHDUL_DE     CHAR(8 BYTE),
  EXECUT_SCHDUL_HOUR   CHAR(2 BYTE),
  EXECUT_SCHDUL_MNT    CHAR(2 BYTE),
  EXECUT_SCHDUL_SECND  CHAR(2 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNNTWRKINFO
(
  NTWRK_ID             CHAR(20 BYTE),
  NTWRK_IP             VARCHAR2(23 BYTE),
  GTWY                 VARCHAR2(23 BYTE),
  SUBNET               VARCHAR2(23 BYTE),
  DOMN_SERVER          VARCHAR2(23 BYTE),
  MANAGE_IEM           VARCHAR2(2 BYTE),
  USER_NM              VARCHAR2(60 BYTE),
  USE_AT               CHAR(1 BYTE),
  REGST_YMD            CHAR(8 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNTROBLINFO
(
  TROBL_ID              CHAR(20 BYTE),
  TROBL_NM              VARCHAR2(60 BYTE),
  TROBL_KND             CHAR(2 BYTE),
  TROBL_DC              VARCHAR2(2000 BYTE),
  TROBL_OCCRRNC_TIME    VARCHAR2(14 BYTE),
  TROBL_RQESTER_NM      VARCHAR2(60 BYTE),
  TROBL_REQUST_TIME     VARCHAR2(14 BYTE),
  TROBL_PROCESS_RESULT  VARCHAR2(2000 BYTE),
  TROBL_OPETR_NM        VARCHAR2(60 BYTE),
  TROBL_PROCESS_TIME    VARCHAR2(14 BYTE),
  PROCESS_STTUS         CHAR(1 BYTE),
  FRST_REGISTER_ID      VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM   DATE,
  LAST_UPDUSR_ID        VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNDAMCALRES
(
  KNO_ID               CHAR(20 BYTE),
  ORGNZT_ID            VARCHAR2(20 BYTE)        DEFAULT NULL,
  SPE_ID               CHAR(20 BYTE)            DEFAULT NULL,
  KNO_TYPE_CD          VARCHAR2(3 BYTE)         DEFAULT NULL,
  EMPLYR_ID            CHAR(20 BYTE)            DEFAULT NULL,
  KNO_NM               VARCHAR2(60 BYTE)        DEFAULT NULL,
  KNO_CN               VARCHAR2(2500 BYTE)      DEFAULT NULL,
  ATCH_FILE_ID         CHAR(20 BYTE)            DEFAULT NULL,
  ANS_PARENTS          CHAR(20 BYTE)            DEFAULT NULL,
  ANS_DEPTH            NUMBER(10)               DEFAULT '0',
  ANS_SEQ              NUMBER(10)               DEFAULT '0',
  ANS_NUMBER           NUMBER(10)               DEFAULT '0',
  FRST_REGISTER_ID     VARCHAR2(20 BYTE)        DEFAULT NULL,
  FRST_REGISTER_PNTTM  DATE                     DEFAULT NULL,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE)        DEFAULT NULL,
  LAST_UPDUSR_PNTTM    DATE                     DEFAULT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNDAMKNOIFM
(
  KNO_ID               CHAR(20 BYTE),
  KNO_TYPE_CD          VARCHAR2(3 BYTE),
  ORGNZT_ID            VARCHAR2(20 BYTE),
  SPE_ID               CHAR(20 BYTE),
  EMPLYR_ID            CHAR(20 BYTE),
  KNO_NM               VARCHAR2(60 BYTE),
  KNO_CN               VARCHAR2(2500 BYTE),
  KEYWORLD             VARCHAR2(100 BYTE),
  OTHBC_AT             CHAR(1 BYTE),
  KNO_APS              CHAR(1 BYTE),
  COL_YMD              CHAR(8 BYTE),
  APP_YMD              CHAR(8 BYTE),
  JUNK_YMD             CHAR(8 BYTE),
  ATCH_FILE_ID         CHAR(20 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNDAMPRO
(
  SPE_ID               CHAR(20 BYTE),
  KNO_TYPE_CD          VARCHAR2(3 BYTE),
  APP_TYPE_CD          CHAR(1 BYTE),
  SPE_CONFM_DE         CHAR(8 BYTE),
  SPE_EXP_CN           VARCHAR2(100 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNDAMMAPKNO
(
  KNO_TYPE_CD          VARCHAR2(3 BYTE),
  ORGNZT_ID            VARCHAR2(20 BYTE),
  SPE_ID               CHAR(20 BYTE),
  KNO_TYPE_NM          VARCHAR2(100 BYTE),
  CL_YMD               CHAR(8 BYTE),
  KNO_URL              VARCHAR2(255 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMTNDAMMAPTEAM
(
  ORGNZT_ID            VARCHAR2(20 BYTE),
  ORGNZT_NM            VARCHAR2(60 BYTE),
  CL_YMD               CHAR(8 BYTE),
  KNO_URL              VARCHAR2(255 BYTE),
  FRST_REGISTER_ID     VARCHAR2(20 BYTE),
  FRST_REGISTER_PNTTM  DATE,
  LAST_UPDUSR_ID       VARCHAR2(20 BYTE),
  LAST_UPDUSR_PNTTM    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
